add user_auth
Spidey03/covid_19_dashboard pull request #3
Opened 2020-07-01 04:03 UTC by Spidey03

2020-07-01 04:19 UTC, raviteja1766 commented on user_auth/admin.py
> +admin.site.register(User, UserAdmin)
Add new line at the end of the file

2020-07-01 04:19 UTC, raviteja1766 commented on user_auth/presenters/presenter_implementation.py
> +from django_swagger_utils.drf_server.exceptions import NotFound, Forbidden
External imports at the top of the file #CleanCode

2020-07-01 04:19 UTC, raviteja1766 commented on user_auth/views/user_login/__init__.py
> +API_ENVIRONMENT = "ENV_MOCK"  # ENV_MOCK / ENV_IMPL
Change into implementation from mock

2020-07-02 16:07 UTC, raviteja1766 commented on ib_miniprojects_backend/settings/.~c9_invoke_7WVLii.py
> +DEFAULT_ACCESS_TOKEN_EXPIRY_IN_SECONDS = 10000000
add new online

2020-07-02 16:08 UTC, raviteja1766 commented on user_auth/constants/exception_messages.py
> +)
add new line

2020-07-02 16:08 UTC, raviteja1766 requested changes
Change those updates

2020-07-02 16:09 UTC, Spidey03 commented on ib_miniprojects_backend/settings/.~c9_invoke_7WVLii.py
> +DEFAULT_ACCESS_TOKEN_EXPIRY_IN_SECONDS = 10000000
I have deleted the file....
It is an unnecessary file

2020-07-02 16:13 UTC, merged